% ==============================================
% Aggiunge una sezione di footer standard in basso alla finestra principale,
% includendo informazioni di copyright e un logo UNIVPM. Da usare in tutte le GUI del progetto.
% ==============================================

function addFooter(parent)
    % === Etichetta di copyright ===
    uilabel(parent, ...
        'Text', sprintf(['\n© 2025 Yurii Riina, Nicol\xf2 Gioacchini, Thomas Marinucci — Tutti i diritti riservati.\n', ...
                         'Questo software è protetto da copyright.'] ), ...
        'FontSize', 10, ...
        'FontName', 'Segoe UI', ...
        'HorizontalAlignment', 'center', ...
        'Position', [100, 10, 700, 35], ...
        'FontColor', [0.5 0.5 0.5], ...
        'BackgroundColor', [0.96 0.96 0.96]);

    % === Logo UNIVPM in basso a sinistra ===
    uiimage(parent, ...
        'ImageSource', 'logo_UNIVPM.png', ...
        'Position', [110 10 80 40], ...
        'ScaleMethod', 'fit');
end